### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [SeriousAlexej/TabToolbar#2]
Hi @SeriousAlexej  good day! I am a graphics designer and i passed by your good project and noticed that it doesn't have a logo that's why i thought of contributing here by designing a logo for free..If you will permit me i will start my design asap.Thanks and best regards! 

-tobaloidee

**Comment by SeriousAlexej** [comment]
Howdy!
Sure, why not, everybody needs to have a portfolio x) Take your time.
Thank you.

**Comment by Tobaloidee** [comment]
here's my logo proposal @SeriousAlexej 

concept: direct visualization of a tab bar, simple and minimal which is visible in small sizes

![offer-05](https://user-images.githubusercontent.com/36028424/41520530-b9f4d9ce-7300-11e8-9cfa-4aa5661eca80.png)

please let me know if you have some modifications or suggestions for me to edit. Thanks!

**Comment by SeriousAlexej** [comment]
The favicon variant looks great, the color is very eye-pleasing.
If you could remove the shadow and leave it flat, that would be awesome.
Or maybe a linear gradient to shadow color from top left corner to right bottom would be even better, that would give the logo a light feeling of shape, but without extra-bulging.
Thank you for your time!

**Comment by Tobaloidee** [comment]
Which color do you prefer before i edit it?

**Comment by SeriousAlexej** [comment]
Blue color from the favicon :)
`#2B81D8`

**Comment by Tobaloidee** [comment]
![tabtoolbar-05](https://user-images.githubusercontent.com/36028424/41539422-57a8a076-7340-11e8-983f-7d91aa68334a.png)

i'll make a PR and upload the SVG and PNG files once you have chosen Sir. :)

**Comment by SeriousAlexej** [comment]
The one with the gradient is very cool, thank you again!

**Comment by Tobaloidee** [comment]
Done with the PR #3 
Thanks so much and Best regards!

-Tobaloidee

**Comment by SeriousAlexej** [comment]
Looks great! Good luck!

**Comment by githubuser0xFFFF** [comment]
@Tobaloidee Hi and sorry for hijacking this thread. I really like your icon that you have designed for this widget. If you would like to design another cool icon for an open source Qt library, then you are welcome to visit https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System.

Maybe you can design a nicer icon than this one:
https://marketplace.qt.io/collections/featured/products/advanced-docking-system

Would be great.
