### ISSUE TITLE
Support for High-DPI screens

### ISSUE THREAD

**Issue by asdfjkl** [SeriousAlexej/TabToolbar#5]
Currently there are issues when high-dpi screens with scaling are used. Consider the attachments for illustration. One is Ubuntu 18.04@1920*1080. The other one is when double scaling was activated in Ubuntu (Settings -> Screen -> Scale -> 200%), 
![100_percent](https://user-images.githubusercontent.com/397515/73817859-5577f400-47ec-11ea-92b4-6b15d430215d.png)
Text under icons is cut off. Also, the size of the icons in the icon group in relation to the larger icons seems to be off.
![200_percent](https://user-images.githubusercontent.com/397515/73817868-5872e480-47ec-11ea-9bb7-e48da90fa35e.png)

**Comment by IngvarRiga** [comment]
Win 10 under 4K Resolution:
![image](https://user-images.githubusercontent.com/23475921/74270820-e5ea9300-4d1c-11ea-8e02-c72753b86252.png)

In qt 5.14, in main module :

```
...................
    //-- Включение масштабирования для экранов с высоким разрешением ?
    **QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);**

    QApplication a(argc, argv);
    MainWindow w;
............
```

And in Linux mint 19.XX on Virtual Machines (4K), also all normal, even when zooming in interface

**Comment by asdfjkl** [comment]
This could be related to https://forum.qt.io/topic/99255/how-to-check-screen-dpi-before-a-qapplication-exists/11 quote "AA_EnableHighDpiScaling needs to be set before a QApplication is started, but on Linux setting this property for a normal non-DPI display will cause everything to be 2x the size on Qt versions under 5.12."

The presented workaround there didn't work for me. 

I assume that mint 19.xx ships with Qt >= 5.12; and the Windows 4k resolution was at higher dpi?

**Comment by IngvarRiga** [comment]
i`m use self-build static lib qt 5.14 on linux mint. And Linux on VM Ware on 27" 4K mon. So... cant check another... Oh, VMWare on Win 10.
